format = """
$character\
$aws\
$username\
$os\

$directory\

$git_branch\
$git_status\

$zig\
$swift\
$scala\
$rust\
$ruby\
$rlang\
$python\
$pijul_channel\
$php\
$perl\
$package\
$ocaml\
$nodejs\
$nix_shell\
$nim\
$meson\
$memory_usage\
$lua\
$kotlin\
$julia\
$java\
$hostname\
$hg_branch\
$haxe\
$haskell\
$guix_shell\
$golang\
$fossil_branch\
$fennel\
$elm\
$elixir\
$docker_context\
$dart\
$crystal\
$conda\
$c\
$buf\

$time\
$character"""

add_newline = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[os]
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[directory]
format = "[ $path/ ]($style)"
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[$symbol $branch ]($style)'

[git_status]
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[  $time ]($style)'

[aws]
symbol = " "
format = '[$symbol ]($style)'
disabled = true

[buf]
symbol = ""
format = '[$symbol ]($style)'

[c]
symbol = " "
format = '[$symbol ]($style)'

[conda]
symbol = " "
format = '[$symbol ]($style)'

[crystal]
symbol = " "
format = '[$symbol ]($style)'

[dart]
symbol = ""
format = '[$symbol ]($style)'

[docker_context]
symbol = " "
format = '[$symbol ]($style)'

[elixir]
symbol = ""
format = '[$symbol ]($style)'

[elm]
symbol = " "
format = '[$symbol ]($style)'

[fennel]
symbol = ""
format = '[$symbol ]($style)'

[fossil_branch]
symbol = " "
format = '[$symbol ]($style)'

[golang]
symbol = ""
format = '[$symbol ]($style)'

[guix_shell]
symbol = " "
format = '[$symbol ]($style)'

[haskell]
symbol = " "
format = '[$symbol ]($style)'

[haxe]
symbol = " "
format = '[$symbol ]($style)'

[hg_branch]
symbol = " "
format = '[$symbol ]($style)'

[hostname]
ssh_symbol = " "
format = '[$symbol ]($style)'

[java]
symbol = " "
format = '[$symbol ]($style)'

[julia]
symbol = " "
format = '[$symbol ]($style)'

[kotlin]
symbol = " "
format = '[$symbol ]($style)'

[lua]
symbol = " "
format = '[$symbol ]($style)'

[memory_usage]
symbol = "󰍛 "
format = '[$symbol ]($style)'

[meson]
symbol = "󰔷 "
format = '[$symbol ]($style)'

[nim]
symbol = "󰆥 "
format = '[$symbol ]($style)'

[nix_shell]
symbol = " "
format = '[$symbol ]($style)'

[nodejs]
symbol = ""
format = '[$symbol ]($style)'

[ocaml]
symbol = " "
format = '[$symbol ]($style)'

[package]
symbol = "󰏗 "
format = '[$symbol ]($style)'

[perl]
symbol = " "
format = '[$symbol ]($style)'

[php]
symbol = " "
format = '[$symbol ]($style)'

[pijul_channel]
symbol = " "
format = '[$symbol ]($style)'

[python]
symbol = " "
format = '[$symbol ]($style)'

[rlang]
symbol = "󰟔 "
format = '[$symbol ]($style)'

[ruby]
symbol = ""
format = '[$symbol ]($style)'

[rust]
symbol = ""
format = '[$symbol ]($style)'

[scala]
symbol = ""
format = '[$symbol ]($style)'

[swift]
symbol = ""
format = '[$symbol ]($style)'

[zig]
symbol = " "
format = '[$symbol ]($style)'

[os.symbols]
Alpaquita = ""
Alpine = " "
Amazon = " "
Android = ""
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓"
Gentoo = " "
HardenedBSD = "󰞌"
Illumos = "󰈸"
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = ""
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺"
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = ""
Windows = "󰍲 "
